# Generated by Django 4.2.23 on 2025-08-13 07:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('lessons', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubmissionResult',
            fields=[
                ('attempt_id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('correct_count', models.IntegerField()),
                ('earned_xp', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('details', models.JSONField(default=dict)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lessons.lesson')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
        ),
    ]
